-- CREATE TABLE IF NOT EXISTS users (
--     user_id INTEGER PRIMARY KEY AUTOINCREMENT,
--     name VARCHAR(255) NOT NULL,
--     email VARCHAR(255) UNIQUE NOT NULL,
--     password VARCHAR(255) NOT NULL
-- );
-- CREATE TABLE IF NOT EXISTS posts (
--     post_id INTEGER PRIMARY KEY,
--     title VARCHAR(255) NOT NULL,
--     content TEXT NOT NULL,
--     createdAt DATETIME NOT NULL,
--     user_id INTEGER,
--     FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
-- );
-- CREATE TABLE IF NOT EXISTS comments (
--     comment_id INTEGER PRIMARY KEY AUTOINCREMENT,
--     post_id INTEGER,
--     content TEXT NOT NULL,
--     FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
-- );
-- CREATE TABLE IF NOT EXISTS likes (
--     like_id INTEGER PRIMARY KEY AUTOINCREMENT,
--     post_id INTEGER,
--     count INTEGER NOT NULL DEFAULT 0,
--     FOREIGN KEY ('post_id') REFERENCES posts(post_id) ON DELETE CASCADE
-- );
-- CREATE TABLE IF NOT EXISTS categories (
--     category_id INTEGER PRIMARY KEY AUTOINCREMENT,
--     name VARCHAR(255) NOT NULL
-- );